### ISSUE TITLE
Feature request: custom intersection in ray query

### ISSUE THREAD

**Issue by seanbaxter** [nvpro-samples/vk_mini_path_tracer#10]
I'd benefit from some checkpoints that show a custom intersection routine in situ for RayQuery, and also through the rint for Trace. The tracedSegments loop in the compute shader is pretty boilerplate, and it could probably be factored away into a function or class template that steps through it but has templated callbacks for intersection and hit logic. It's been suggested to me that lambdas would be a good way to customize rayQuery without requiring the user to write the state machine.

**Comment by NBickford-NV** [comment]
Hi Sean! This does sound like a good use case for Circle C++ - have you taken a look at the intersection shader sample in `vk_raytracing_tutorial_KHR` at https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/tree/master/ray_tracing_intersection? I think this might answer the question for the ray tracing pipeline, but not ray queries.

**Comment by seanbaxter** [comment]
Ya, that raytracing tutorial has a lot of stuff buried. Will get to it asap.
