### ISSUE TITLE
triangles.maxVertex seems to get a wrong value

### ISSUE THREAD

**Issue by shiuang** [nvpro-samples/vk_mini_path_tracer#11]
In
https://github.com/nvpro-samples/vk_mini_path_tracer/blob/6095e1d4bc57e6f3010709868931d9cbb16207bf/vk_mini_path_tracer/main.cpp#L143
objVertices.size() - 1 is assigned to triangles.maxVertex. Since objVertices is a vector of floats instead of a vector of vertices, the size of objVertices indicates total number of floats (3x number of vertices).

In [Vulkan specs](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkAccelerationStructureGeometryTrianglesDataKHR.html)
> maxVertex is the highest index of a vertex that will be addressed by a build command using this structure.

So objVertices.size() / 3 - 1 should be the correct value if I got it right.

BTW, it is also confusing that Vulkan uses highest index of a vertex instead of number of vertices, while the [DirectX API](https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html#d3d12_raytracing_geometry_triangles_desc) uses VertexCount in D3D12_RAYTRACING_GEOMETRY_TRIANGLES_DESC struct. Does anyone know why?

**Comment by NBickford-NV** [comment]
Hi shiuang! I think you're correct - I've fixed this upstream, and this should be included in the next nvpro-samples bulk update (I'll close the issue then). I don't know about the VertexCount difference, unfortunately!

**Comment by shiuang** [comment]
Thank you for your reply, NeilBickford-NV.

**Comment by NBickford-NV** [comment]
Alright, this has been fixed in commit 5cf2ea9 - thanks again!
