### ISSUE TITLE
Typos and Changes in the Tutorial Text

### ISSUE THREAD

**Issue by LonelyQuantum** [nvpro-samples/vk_mini_path_tracer#13]
Platform: Windows 10
The incoherence of the codes in the tutorial and that in the checkpoint files might be due to the changes in VulkanAPI and nvvk files.

### Section 8.1 Including Additional Headers
The tinyobjloader should be included by `#include <tiny_obj_loader.h>` instead of `#include <fileformats/tiny_obj_loader.h>`. It now locates at `nvpro_core/third_party` folder.

### Section 8.6.3 Creating the TLAS
The codes for creating TLASes 

```
// Create an instance pointing to this BLAS, and build it into a TLAS:
std::vector<nvvk::RaytracingBuilderKHR::Instance> instances;
{
  nvvk::RaytracingBuilderKHR::Instance instance;
  instance.transform.identity();  // Set the instance transform to the identity matrix
  instance.instanceCustomId = 0;  // 24 bits accessible to ray shaders via rayQueryGetIntersectionInstanceCustomIndexEXT
  instance.blasId           = 0;  // The index of the BLAS in `blases` that this instance points to
  instance.hitGroupId = 0;  // Used for a shader offset index, accessible via rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT
  instance.flags = VK_GEOMETRY_INSTANCE_TRIANGLE_FACING_CULL_DISABLE_BIT_KHR;  // How to trace this instance
  instances.push_back(instance);
}
```
should be replaced by 

```
// Create an instance pointing to this BLAS, and build it into a TLAS:
std::vector<VkAccelerationStructureInstanceKHR> instances;
{
  VkAccelerationStructureInstanceKHR instance{};
  instance.transform = nvvk::toTransformMatrixKHR(nvmath::mat4f(1));  // Set the instance transform to the identity matrix
  instance.instanceCustomIndex = 0;  // 24 bits accessible to ray shaders via rayQueryGetIntersectionInstanceCustomIndexEXT
  instance.accelerationStructureReference = raytracingBuilder.getBlasDeviceAddress(0);  // The address of the BLAS in blases that this instance points to
  // Used for a shader offset index, accessible via rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT
  instance.instanceShaderBindingTableRecordOffset = 0;
  instance.flags = VK_GEOMETRY_INSTANCE_TRIANGLE_FACING_CULL_DISABLE_BIT_KHR;  // How to trace this instance
  instance.mask = 0xFF;
  instances.push_back(instance);
}
```
It seems that something happened here is that Vulkan incorporated the support of TLAS into their own API.

### Section 11.5 Offsetting the Ray Origin
When introducing the GLSL `faceforward` function, it says 

> (in our case, genType is vec3). This function returns N or -N depending on the directions I (like an incoming light vector) and Nref (like a normal of a surface). If I and Nref point towards each other (i.e. their angles differ by more than 180°), then this returns N. Otherwise (if I and Nref point within 180° of the same direction), then this returns -N.

It is confusing. I think it is better to say if they differ more than 90°, which is also coherent with the expressions in "The Dot Product" block below.

### Section Extra 7.3 Synchronization, Part 3: Layout Transitions and Image Memory Barriers
The `nvvk::makeImageMemoryBarrier` will not be found unless we include `#include <nvvk/images_vk.hpp>`

### Section Extra 7.9 Mapping, Reading, and Unmapping
`  NVVK_CHECK(vkMapMemory(context, imageLinear.allocation, 0, VK_WHOLE_SIZE, 0, &data));` won't work as `nvvk::Image` has no member `allocation`. Should stick to something like 
```
void* data = allocator.map(imageLinear);
stbi_write_hdr("out.hdr", render_width, render_height, 4, reinterpret_cast<float*>(data));
allocator.unmap(imageLinear);
```

### Section Extra 9.5 Creating the Scene
The same problem as in **Section 8.6.3 Creating the TLAS**. We should replace `nvvk::RaytracingBuilderKHR::Instance` by `VkAccelerationStructureInstanceKHR `, and `instance.transform.identity(); ` by `instance.transform = nvvk::toTransformMatrixKHR(nvmath::mat4f(1));` etc.

**Comment by NBickford-NV** [comment]
Hi LonelyQuantum - thanks for all the typo reports, they're much appreciated! I think these should all be fixed now in commit 408e777, which also adds a bit more info about TLAS creation and fixes a few other things I spotted. Most were indeed due to changes in nvpro_core that weren't updated in the tutorial.

The faceforward description was especially incorrect (I think I probably did the radians -> degrees conversion wrong in my head when writing that), and is now fixed! 90° was the correct number there.

Thanks again! Please let me know if you find any more typos.
