### ISSUE TITLE
Error When Switching from Debug to Release Mode in VS2022

### ISSUE THREAD

**Issue by LonelyQuantum** [nvpro-samples/vk_mini_path_tracer#14]
I am using Visual Studio 2022 17.0.4 on Windows 10

When I am following the instructions in **Extra Section 2.1 Preparing for Analysis** , it required making a release-mode build of the project. However, when I switch to a release build, the Linker failed to open the input files.

The output says it fail to generate the projects `imgui`, `glfw`, `basisu`, and `nvpro_core `with error `value cannot be null` and parameter name `path1`

---------------------------------------------------------
Update:
According to [Error: Value cannot be nul](https://developercommunity.visualstudio.com/t/error-value-cannot-be-null/1567360)
It is fixed after restarting VS. I am not sure the reason of this problem, which could be a bug of VS2022

**Comment by NBickford-NV** [comment]
Interesting! I haven't tested this on Visual Studio 2022 yet, so it could be a bug with that. My initial guess was going to be that the imgui, glfw, and basisu submodules weren't downloaded (running `git submodule update --init --recursive` in nvpro_core would fix that), but glad you were able to solve it!
