### ISSUE TITLE
Wrong code example for the identity matrix

### ISSUE THREAD

**Issue by tmarrec** [nvpro-samples/vk_mini_path_tracer#15]
https://github.com/nvpro-samples/vk_mini_path_tracer/blob/f29c5b9d5146259ba0fc8e5840736c249bec340f/docs/extras.html#L2014

The code is wrong here, we should not set "transform" to an (1,0,0) translation matrix.

**Comment by NBickford-NV** [comment]
Thanks Tristan - good catch! I've fixed this in commit [4a438ea](https://github.com/nvpro-samples/vk_mini_path_tracer/commit/4a438ea3313ebeb9f416ac2c168ba6dc4f3c0a59), and the code should now read

```
transform.identity();
```

Thanks again!
