### ISSUE TITLE
Typo and deadlink

### ISSUE THREAD

**Issue by j3soon** [nvpro-samples/vk_mini_path_tracer#17]
Some typos found when following the tutorial:

- `bufer` -> `buffer`
- `vkrt_tutorial.md.htm` -> `vkrt_tutorial.md`

See [here](https://github.com/nvpro-samples/vk_mini_path_tracer/compare/main...j3soon:vk_mini_path_tracer:minor-fixes) for diff.

<hr>

**Update**: found some more typos by [codespell](https://github.com/codespell-project/codespell):

```sh
codespell index.html extras.html -L inout
```

will open a pull request.

**Comment by NBickford-NV** [comment]
Fixed by merging #18 . Thank you again!
