### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by kirill146** [nvpro-samples/vk_mini_path_tracer#19]
This link seems to be dead. Not sure were it should lead
https://github.com/nvpro-samples/vk_mini_path_tracer/blob/4d93aea128e3ccb8b1176ee6443c22caca644bac/docs/index.html#L4158

**Comment by NBickford-NV** [comment]
Thanks @kirill146 ! This page moved to https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/blob/master/ray_tracing_anyhit/README.md; I've fixed the link in https://github.com/nvpro-samples/vk_mini_path_tracer/commit/127f0596bbbcf7393631dcae74c351d99e0fc0c1. Thanks again!
